### ISSUE TITLE
annotorious-vanilla-rest-plugin: API request failed: '200'

### ISSUE THREAD

**Issue by jafojial** [annotorious/annotorious-vanilla-rest-plugin#2]
Hello!
I use  to save and load annatorious annotations from Mysql database. I already save annotations and now when I want to load them from database, I obtain the error message " API request failed: '200' " and the notification "Sorry we could not load this annotation".
My Response data are: 
{[{"id":3,"src":"http://localhost:8080/Annotations/640px-Hallstatt.jpg","text":"Encore une autre","shapes"
:"[{\"geometry\":{\"x\":0.175,\"width\":0.25,\"y\":0.4875,\"height\":0.2125},\"type\":\"rect\"}]","context"
:"http://localhost:8080/Annotations/index.jsp","type":"highlighted"},{"id":2,"src":"http://localhost
:8080/Annotations/640px-Hallstatt.jpg","text":"Another annotation","shapes":"[{\"geometry\":{\"x\":0
.1375,\"width\":0.253125,\"y\":0.5,\"height\":0.12},\"type\":\"rect\"}]","context":"http://localhost
:8080/Annotations/index.jsp","type":"highlighted"},{"id":1,"src":"http://localhost:8080/Annotations/640px-Hallstatt
.jpg","text":"Really this is my first annotation.","shapes":"[{\"geometry\":{\"x\":0.215625,\"width\"
:0.2171875,\"y\":0.565,\"height\":0.145},\"type\":\"rect\"}]","context":"http://localhost:8080/Annotations
/index.jsp","type":"highlighted"}]}
Please need help! what is wrong?

**Comment by rsimon** [comment]
Hi,

it seems that when you return the annotation JSON, you're not properly serializing the geometry:

"shapes":"[{\"geometry\":{\"x\":0.175,\"width\":0.25,\"y\":0.4875,\"height\":0.2125},\"type\":\"rect\"}]"

as you can see, the value of the "shapes" property is a string, whereas it should be a JSON element. (I assume you are storing this as a string in your SQL-DB and then just pulling it out without parsing it back to JSON.) The way it should be is:

"shapes":[{"geometry":{"x":0.175, "width":0.25,"y":0.4875,"height":0.2125},"type":"rect"}]

Cheers,
Rainer

________________________________________
Von: Alex JAZA [notifications@github.com]
Gesendet: Mittwoch, 17. Juni 2015 11:12
An: annotorious/annotorious-vanilla-rest-plugin
Betreff: [annotorious-vanilla-rest-plugin] annotorious-vanilla-rest-plugin: API request failed: '200' (#2)

Hello!
I use to save and load annatorious annotations from Mysql database. I already save annotations and now when I want to load them from database, I obtain the error message " API request failed: '200' " and the notification "Sorry we could not load this annotation".
My Response data are:
{[{"id":3,"src":"http://localhost:8080/Annotations/640px-Hallstatt.jpg","text":"Encore une autre","shapes"
:"[{\"geometry\":{\"x\":0.175,\"width\":0.25,\"y\":0.4875,\"height\":0.2125},\"type\":\"rect\"}]","context"
:"http://localhost:8080/Annotations/index.jsp","type":"highlighted"},{"id":2,"src":"http://localhost
:8080/Annotations/640px-Hallstatt.jpg","text":"Another annotation","shapes":"[{\"geometry\":{\"x\":0
.1375,\"width\":0.253125,\"y\":0.5,\"height\":0.12},\"type\":\"rect\"}]","context":"http://localhost
:8080/Annotations/index.jsp","type":"highlighted"},{"id":1,"src":"http://localhost:8080/Annotations/640px-Hallstatt
.jpg","text":"Really this is my first annotation.","shapes":"[{\"geometry\":{\"x\":0.215625,\"width\"
:0.2171875,\"y\":0.565,\"height\":0.145},\"type\":\"rect\"}]","context":"http://localhost:8080/Annotations
/index.jsp","type":"highlighted"}]}
Please need help! what is wrong?

�

**Comment by jafojial** [comment]
Hi,
I use a annotation Beans with shapes attribute as String and I don't know how I can parsing it back to JSON. 
Please could you give me some ideas?

**Comment by rsimon** [comment]
Hi,

I'm afraid that's entirely dependent on what kind of technology you use on the server to handle the JSON in the first place. (In any case, it's an issue entirely independent from Annotorious, or client-side JavaScript in general.) How do you parse the JSON that's incoming from the client? I.e. how are you getting from shapes JSON fragment to string? There must surely be a way in the library you use that works the other way round.

Cheers,
R


________________________________________
Von: Alex JAZA [notifications@github.com]
Gesendet: Mittwoch, 17. Juni 2015 11:35
An: annotorious/annotorious-vanilla-rest-plugin
Cc: Simon Rainer
Betreff: Re: [annotorious-vanilla-rest-plugin] annotorious-vanilla-rest-plugin: API request failed: '200' (#2)

Hi,
I use a annotation Beans with shapes attribute as String and I don't know how I can parsing it back to JSON.
Please could you give me some ideas?

�

**Comment by jafojial** [comment]
Thank you rsimon. 
It was effectively a JSON parse problem. I stored my shapes as a String but now I store each parameter of shapes (type, x, y, width, height) and this resolve my problem.
